name: Test and Publish StravaCZ

on:
  push:
    branches: [ main ]
    tags: ['v*.*.*']
  pull_request:
    branches: [ main ]
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12']
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}-
            ${{ runner.os }}-pip-
      
      - run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - run: pytest -v --cov=strava_cz --cov-report=xml
      
      - run: flake8 src/strava_cz --max-line-length=100
      
      - run: black --check src/strava_cz
      
      - run: mypy src/strava_cz --ignore-missing-imports

  build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - run: |
          python -m pip install --upgrade pip build twine
          python -m build
      
      - run: |
          python -m twine upload dist/* \
            -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
